NumPy Arrays: 1D -> 2D

In [1]:
my_list = [1, 2, 3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [11]:
my_mat = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.arange()

In [13]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

np.zeros()

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.ones()

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

np.linspace 第三个是均匀分布的个数

In [21]:
np.linspace(0, 5, 9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

np.eye()

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

np.random.rand(), np.random.rannd(), np.random.randint()

In [23]:
np.random.rand(5)

array([0.8395055 , 0.71346504, 0.64939383, 0.65225863, 0.63272604])

In [24]:
np.random.rand(5,5)

array([[0.61176517, 0.80349065, 0.68206562, 0.21048754, 0.43408373],
       [0.72351028, 0.13738085, 0.89477243, 0.78186693, 0.44213644],
       [0.00160117, 0.47228952, 0.86971178, 0.75761888, 0.9870395 ],
       [0.52394973, 0.71189766, 0.28444982, 0.66528651, 0.32589945],
       [0.16796382, 0.73427282, 0.45658226, 0.88341016, 0.96809266]])

In [25]:
np.random.randn(3)

array([ 0.06573144,  0.25933119, -1.27161469])

In [26]:
np.random.randn(4,4)

array([[ 0.18596003, -0.18730235, -0.47328827, -0.01342512],
       [-0.6254787 ,  0.04588858, -0.5232059 , -0.48191327],
       [-0.09153886,  1.18718656,  1.70960854, -0.50919302],
       [ 1.21464154, -0.49047136, -0.10658628, -0.44961641]])

In [27]:
np.random.randint(1, 100, 10)

array([15, 83, 86, 63, 80, 63, 35, 26, 26, 80])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0, 50, 10)

In [31]:
ranarr

array([26, 12, 33, 47, 18,  8, 16, 18, 18, 36])

arr.reshape(), 5 * 5 = 25,arr满足共25个数

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.reshape(5,2)

array([[26, 12],
       [33, 47],
       [18,  8],
       [16, 18],
       [18, 36]])

ranarr.max(),ranarr.min(); index: ranarr.argmax(), ranarr.argmin()

In [34]:
ranarr.max()

47

In [35]:
ranarr.min()

8

In [36]:
ranarr.argmax()

3

In [37]:
ranarr.argmin()

5

In [40]:
arr = arr.reshape(5,5)

In [41]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

arr.shape, arr.dtype

In [42]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int64')

简写: from numpy.random import randint, 直接用randit

In [45]:
from numpy.random import randint

In [46]:
randint(2, 10)

6